@url=http://localhost:5238

GET {{url}}/exceptiontest HTTP/1.1

###
GET {{url}}/dbsqlite/fill HTTP/1.1

###
GET {{url}}/dbsqlite/create HTTP/1.1

###

GET {{url}}/robots HTTP/1.1

###
GET {{url}}/robots/withweapons HTTP/1.1

###
GET {{url}}/robots/2 HTTP/1.1

###
GET {{url}}/robots/3/withweapons HTTP/1.1

###
GET {{url}}/robots/99 HTTP/1.1

###
GET {{url}}/robots/weaponslist HTTP/1.1

### TESTER L'EXISTENCE D'UNE WEAPON
GET {{url}}/robots/isweaponexists?id=1&name=Little%20Fire%20Gun HTTP/1.1
###
GET {{url}}/robots/isweaponexists?id=3&name=Little%20Fire%20Gun HTTP/1.1
###
GET {{url}}/robots/isweaponexists?id=1&name=Little%20FireGun HTTP/1.1

### FIN TESTER

###
POST {{url}}/robots HTTP/1.1
Content-Type: application/json

{
    "codeName": "ERO-34"
}

###
POST {{url}}/robots HTTP/1.1
Content-Type: application/json

{
    "codeName": ""
}
###
POST {{url}}/robots HTTP/1.1
Content-Type: application/json

{
    "codeName": "O"
}
###
POST {{url}}/robots HTTP/1.1
Content-Type: application/json

{
    "codeName": "TR12-456-AAA-678"
}
###
PUT {{url}}/robots/2 HTTP/1.1
Content-Type: application/json

{
    "codeName": "MIC-HEL9"
}
###
PUT {{url}}/robots/2 HTTP/1.1
Content-Type: application/json

{
    "codeName": ""
}
###
DELETE {{url}}/robots/2 HTTP/1.1
###
DELETE {{url}}/robots/222 HTTP/1.1

